# config/packages/easy_admin.yaml
easy_admin:
  entities:
    Etablissement:
      list:
        fields:
          - { property: 'image', type: 'image', base_path: '%etab_images%' }
      show:
        fields:
          - { property: 'image', type: 'image', base_path: '%etab_images%' }
      form:
        fields:
          - { property: 'imageFile', type: 'file' }

    Suite:
      list:
        fields:
          - { property: 'main_image', type: 'image', base_path: '%suite_images%' }
      show:
        fields:
          - { property: 'main_image', type: 'image', base_path: '%suite_images%' }
      form:
        fields:
          - { property: 'imageFile', type: 'file' }