vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        etab_images:
            uri_prefix: '%etab_images%'
            upload_destination: '%kernel.project_dir%/public%etab_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
        suite_images:
            uri_prefix: '%suite_images%'
            upload_destination: '%kernel.project_dir%/public%suite_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
        galerie_images:
            uri_prefix: '%galerie_images%'
            upload_destination: '%kernel.project_dir%/public%galerie_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true