vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute

    mappings:
        etab_images:
            uri_prefix: '%etab_images%'
            upload_destination: etablissements.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
        suite_images:
            uri_prefix: '%suite_images%'
            upload_destination: suites.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
        galerie_images:
            uri_prefix: '%galerie_images%'
            upload_destination: galerie.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true